Repository Mellanox/libxlio, pull requests merged in 2024-08, with the labels that each got.

#143 issue: 3928006 Remove unused XLIO_BF
  README
  src/core/main.cpp
  src/core/util/sys_vars.cpp
  src/core/util/sys_vars.h
Labels: to_merge

#151 [CI]: Remove the Ubuntu-20.x support
  .ci/matrix_job.yaml
Labels: draft

#222 issue: 3898109 Bump to DOCA version 2.9.0029
  .ci/dockerfiles/Dockerfile.ubuntu22.04
  config/m4/doca.m4
  contrib/jenkins_tests/globals.sh
Labels: XLIO_DOCA
