Repository Mellanox/libxlio, pull requests merged in 2025-05, with the labels that each got.

#326 issue: 4347777 Replace thread-local dummy lock with global one
  src/core/dev/ring_slave.cpp
  src/core/sock/sockinfo_tcp.cpp
  src/utils/lock_wrapper.h
  tests/gtest/tcp/tcp_socket.cc
Labels: Review effort 3/5

#297 issue: 4043235 TCP_USER_TIMER wrong RTO behavior
  src/utils/rdtsc.h
Labels: Review effort 2/5

#323 issue: 4213201 Nullify all WQEBB on special WQEs
  src/core/dev/hw_queue_tx.cpp
Labels: Review effort 4/5

#350 [CI] migrate CI test steps to containers - Valgrind
  .ci/dockerfiles/Dockerfile.ubuntu22.04
  .ci/matrix_job.yaml
  contrib/jenkins_tests/globals.sh
  contrib/jenkins_tests/vg.sh
Labels: Review effort 4/5

#347 Issue #4377705: Create tar.gz from src.rpm
  .ci/do_release.sh
  contrib/build_pkg.sh
Labels: Review effort 4/5

#360 [CI] issue: HPCINFRA-3633 Migrate CI test steps to containers - Test
  .ci/dockerfiles/Dockerfile.ubuntu22.04
  .ci/matrix_job.yaml
  contrib/jenkins_tests/test.sh
Labels: Review effort 4/5
